version: 2
updates:
  - package-ecosystem: "npm"   # pnpmでもここは npm 扱いのことが多い（内部でpnpm検出する）
    directory: "/"             # ← 重要：workspaceルート
    schedule:
      interval: "weekly"
    target-branch: "develop"

    groups:
      web-deps:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "tailwindcss"
          - "@tailwindcss/*"
          - "tailwind-merge"
          - "@storybook/*"
          - "storybook"
          - "lucide-react"
          - "@typescript-eslint/*"
          - "typescript-eslint"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "Django"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
