version: "3.9"
services:
  db:
    image: postgis/postgis:16-3.4
    container_name: jinja_postgis16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jinja_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: jdb50515
      TZ: Asia/Tokyo
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d jinja_app"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pg_data:
