# Dockerfile.frontend
FROM node:20-slim

WORKDIR /app

# lightningcss が必要とする依存ライブラリ
RUN apt-get update && apt-get install -y \
    libc6 \
    build-essential \
    python3 \
    && rm -rf /var/lib/apt/lists/*

# package.json と lock ファイルだけコピー
COPY package*.json ./

RUN npm install

# アプリ本体をコピー
COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]
