[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
# まずは致命系＋import整形のみ
select = ["E", "F", "I"]
ignore = ["E501"]

# flake8 を使う場合は backend/.flake8 に置いてください。
# pyproject.toml に置きたい場合は TOML 配列で:
# [tool.flake8]
# max-line-length = 120
# extend-ignore = ["E203", "W503"]
# per-file-ignores = [
#   "temples/migrations/*.py: F401,E501",
#   "users/migrations/*.py: F401,E501",
#   "temples/tests/**: F401,F841,E402,E501",
#   "tmp_*.py: F401,E402",
# ]
