# Generated by Django 5.2.5 on 2025-08-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prefecture', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('principal_image', models.CharField(blank=True, help_text='本尊（例: 聖観音）', max_length=200)),
                ('benefits', models.CharField(blank=True, help_text='ご利益（カンマ区切り）', max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
