# Generated by Django 5.2.5 on 2025-08-18 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0003_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shrine',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='shrine',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shrines', to=settings.AUTH_USER_MODEL),
        ),
    ]
