# Generated by Django 5.2.5 on 2025-08-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0004_alter_shrine_options_shrine_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrine',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='prefecture',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
