# Generated by Django 5.2.5 on 2025-09-03 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('temples', '0015_drop_legacy_fields_and_add_unique_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temples.shrine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='favorites_f_user_id_27e810_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'shrine'), name='unique_user_shrine')],
            },
        ),
    ]
