# Generated by Django 5.2.5 on 2025-10-13 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="favorite",
            name="favorites_f_user_id_5e9d49_idx",
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="target_type",
            field=models.CharField(choices=[("shrine", "Shrine")], max_length=20),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "target_type", "target_id"),
                name="uniq_favorite_per_user_and_target",
            ),
        ),
    ]
