# Generated by Django 5.2.5 on 2025-08-22 12:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_jp', models.CharField(max_length=100)),
                ('name_romaji', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('goriyaku', models.TextField(blank=True, default='', help_text='ご利益', null=True)),
                ('sajin', models.TextField(blank=True, default='', help_text='祭神', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goshuin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='goshuin/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='goshuin/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='goshuin/')),
                ('is_public', models.BooleanField(default=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goshuins', to='temples.shrine')),
            ],
        ),
        migrations.CreateModel(
            name='ViewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temples.shrine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('shrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='temples.shrine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_shrines', to=settings.AUTH_USER_MODEL)),
                ('shrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='temples.shrine')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'shrine')},
            },
        ),
    ]
