# Generated by Django 5.2.5 on 2025-08-23 11:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoriyakuTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='shrine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shrine',
            name='element',
            field=models.CharField(blank=True, help_text='五行属性: 木火土金水', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], default='added', max_length=10),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='goriyaku',
            field=models.TextField(blank=True, default='', help_text='ご利益（自由メモ）', null=True),
        ),
        migrations.AlterField(
            model_name='viewlike',
            name='shrine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewlikes', to='temples.shrine'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shrine',
            name='goriyaku_tags',
            field=models.ManyToManyField(blank=True, related_name='shrines', to='temples.goriyakutag'),
        ),
        migrations.CreateModel(
            name='RankingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('shrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_logs', to='temples.shrine')),
            ],
            options={
                'unique_together': {('shrine', 'date')},
            },
        ),
    ]
