# Generated by Django 5.2.5 on 2025-08-26 01:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0002_goriyakutag_shrine_description_shrine_element_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrine',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
