# backend/temples/migrations/0005_add_shrine_location.py
# Generated by Django 5.2.5 on 2025-09-03 05:07

import django.contrib.gis.db.models.fields
from django.db import migrations


def _enable_postgis(apps, schema_editor):
    # ✅ PostgreSQL のときだけ PostGIS を有効化。SQLite(Spatialite) では何もしない
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cur:
        cur.execute("CREATE EXTENSION IF NOT EXISTS postgis")


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0004_enforce_nonnull_shrine_fields"),
    ]

    operations = [
        # 🔁 RunSQL をやめ、条件付き RunPython に変更
        migrations.RunPython(_enable_postgis, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="shrine",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, null=True, blank=True),
        ),
    ]
