# Generated by Django 5.2.5 on 2025-08-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0004_conciergehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='goriyakutag',
            name='category',
            field=models.CharField(default='ご利益', max_length=50),
        ),
    ]
