# Generated by Django 5.2.5 on 2025-08-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0005_goriyakutag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goriyakutag',
            name='category',
            field=models.CharField(choices=[('ご利益', '願望・テーマ別'), ('神格', '祭神の種類'), ('地域', '地域や役割')], default='ご利益', max_length=50),
        ),
    ]
