# Generated by Django 5.2.5 on 2025-09-03 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0006_remove_shrine_name_alter_shrine_owner"),
    ]

    operations = []
