# Generated by Django 5.2.5 on 2025-09-03 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0008_drop_legacy_name"),
    ]

    operations = []
