# Generated by Django 5.2.5 on 2025-09-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0009_force_drop_legacy_name_short'),
    ]

    operations = [
    ]
