# Generated by Django 5.2.5 on 2025-09-03 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0010_relax_and_drop_legacy_name"),
    ]

    operations = []
