# Generated by Django 5.2.5 on 2025-09-03 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0011_drop_name_final"),
    ]

    operations = []
