# Generated by Django 5.2.5 on 2025-09-03 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0013_drop_legacy_name_column"),
    ]

    operations = []
