# Generated by Django 5.2.5 on 2025-09-06 13:52

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0015_safe_drop_legacy_and_unique_favorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceRef",
            fields=[
                (
                    "place_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("snapshot_json", models.JSONField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "place_ref",
            },
        ),
        migrations.AlterModelOptions(
            name="goriyakutag",
            options={"ordering": ["category", "name"]},
        ),
        migrations.AlterModelOptions(
            name="shrine",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterField(
            model_name="shrine",
            name="latitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="shrine",
            name="longitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ]
            ),
        ),
        migrations.AddIndex(
            model_name="goriyakutag",
            index=models.Index(fields=["category", "name"], name="temples_gor_categor_761fec_idx"),
        ),
        migrations.AddIndex(
            model_name="shrine",
            index=models.Index(fields=["name_jp"], name="temples_shr_name_jp_2d623e_idx"),
        ),
        migrations.AddIndex(
            model_name="shrine",
            index=models.Index(fields=["updated_at"], name="temples_shr_updated_7a628a_idx"),
        ),
        migrations.AddIndex(
            model_name="viewlike",
            index=models.Index(fields=["created_at"], name="temples_vie_created_764544_idx"),
        ),
        migrations.AddIndex(
            model_name="viewlike",
            index=models.Index(fields=["is_like"], name="temples_vie_is_like_5492f0_idx"),
        ),
        migrations.AddIndex(
            model_name="placeref",
            index=models.Index(fields=["name"], name="place_ref_name_63fd60_idx"),
        ),
        migrations.AddIndex(
            model_name="placeref",
            index=models.Index(fields=["synced_at"], name="place_ref_synced__310299_idx"),
        ),
    ]
