# Generated by Django 5.2.5 on 2025-09-11 17:10

import django.contrib.postgres.indexes
from django.db import migrations

# Postgres-specific indexes may not be available/appropriate in test DBs (SQLite).
try:
    from django.contrib.postgres.indexes import GinIndex, GistIndex
except Exception:
    GinIndex = None
    GistIndex = None
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0021_enable_postgis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoshuinImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="goshuin/")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="viewlike",
            name="shrine",
        ),
        migrations.RemoveField(
            model_name="viewlike",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="rankinglog",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="goshuin",
            name="image1",
        ),
        migrations.RemoveField(
            model_name="goshuin",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="goshuin",
            name="image3",
        ),
        migrations.AlterField(
            model_name="rankinglog",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        # Add Postgres-specific indexes only if running against PostgreSQL.
        migrations.RunPython(
            lambda apps, schema_editor: (
                schema_editor.add_index(
                    apps.get_model("temples", "PlaceRef"),
                    GinIndex(fields=["snapshot_json"], name="placeref_snapshot_gin"),
                )
                if GinIndex is not None and schema_editor.connection.vendor == "postgresql"
                else None
            )
        ),
        migrations.RunPython(
            lambda apps, schema_editor: (
                schema_editor.add_index(
                    apps.get_model("temples", "Shrine"),
                    GistIndex(fields=["location"], name="shrine_location_gist"),
                )
                if GistIndex is not None and schema_editor.connection.vendor == "postgresql"
                else None
            )
        ),
        migrations.AddConstraint(
            model_name="rankinglog",
            constraint=models.UniqueConstraint(
                fields=("shrine", "date"), name="uq_rankinglog_shrine_date"
            ),
        ),
        migrations.AddField(
            model_name="goshuinimage",
            name="goshuin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="temples.goshuin",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="shrine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="temples.shrine",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="ViewLike",
        ),
        migrations.AddIndex(
            model_name="goshuinimage",
            index=models.Index(fields=["order"], name="temples_gos_order_27aae0_idx"),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("shrine", "user"), name="uq_like_shrine_user"
            ),
        ),
    ]
