# Generated by Django 5.2.5 on 2025-09-11 17:10

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0021_enable_postgis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoshuinImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="goshuin/")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="viewlike",
            name="shrine",
        ),
        migrations.RemoveField(
            model_name="viewlike",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="rankinglog",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="goshuin",
            name="image1",
        ),
        migrations.RemoveField(
            model_name="goshuin",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="goshuin",
            name="image3",
        ),
        migrations.AlterField(
            model_name="rankinglog",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddIndex(
            model_name="placeref",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["snapshot_json"], name="placeref_snapshot_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="shrine",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["location"], name="shrine_location_gist"
            ),
        ),
        migrations.AddConstraint(
            model_name="rankinglog",
            constraint=models.UniqueConstraint(
                fields=("shrine", "date"), name="uq_rankinglog_shrine_date"
            ),
        ),
        migrations.AddField(
            model_name="goshuinimage",
            name="goshuin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="temples.goshuin",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="shrine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="temples.shrine",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="ViewLike",
        ),
        migrations.AddIndex(
            model_name="goshuinimage",
            index=models.Index(fields=["order"], name="temples_gos_order_27aae0_idx"),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("shrine", "user"), name="uq_like_shrine_user"
            ),
        ),
    ]
