# Generated by Django 5.2.5 on 2025-09-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0022_goshuinimage_like_remove_viewlike_shrine_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shrine",
            index=models.Index(fields=["latitude"], name="idx_shrine_lat"),
        ),
        migrations.AddIndex(
            model_name="shrine",
            index=models.Index(fields=["longitude"], name="idx_shrine_lng"),
        ),
        migrations.AddIndex(
            model_name="shrine",
            index=models.Index(fields=["latitude", "longitude"], name="idx_shrine_lat_lng"),
        ),
    ]
