# Generated by Django 5.2.5 on 2025-09-17 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0023_fix_str_methods_and_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'shrine')},
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'created_at'], name='idx_fav_user_created'),
        ),
    ]
