# Generated by Django 4.2.24 on 2025-09-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temples', '0023_fix_str_methods_and_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shrine',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='favorite_exactly_one_target',
        ),
        migrations.RemoveIndex(
            model_name='shrine',
            name='temples_shr_name_jp_2d623e_idx',
        ),
        migrations.RemoveIndex(
            model_name='shrine',
            name='temples_shr_updated_7a628a_idx',
        ),
        migrations.RemoveIndex(
            model_name='shrine',
            name='shrine_popular_idx',
        ),
        migrations.RemoveIndex(
            model_name='shrine',
            name='shrine_location_gist',
        ),
        migrations.RemoveIndex(
            model_name='shrine',
            name='idx_shrine_lat',
        ),
        migrations.RemoveIndex(
            model_name='shrine',
            name='idx_shrine_lng',
        ),
        migrations.RemoveIndex(
            model_name='shrine',
            name='idx_shrine_lat_lng',
        ),
        migrations.RemoveField(
            model_name='shrine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shrine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shrine',
            name='element',
        ),
        migrations.RemoveField(
            model_name='shrine',
            name='favorites_30d',
        ),
        migrations.RemoveField(
            model_name='shrine',
            name='goriyaku',
        ),
        migrations.RemoveField(
            model_name='shrine',
            name='goriyaku_tags',
        ),
        migrations.RemoveField(
            model_name='shrine',
            name='last_popular_calc_at',
        ),
        migrations.RemoveField(
            model_name='shrine',
            name='location',
        ),
        migrations.RemoveField(
            model_name='shrine',
            name='popular_score',
        ),
        migrations.RemoveField(
            model_name='shrine',
            name='sajin',
        ),
        migrations.RemoveField(
            model_name='shrine',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='shrine',
            name='views_30d',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('shrine__isnull', False), ('place_id__isnull', True)), models.Q(('shrine__isnull', True), ('place_id__isnull', False)), _connector='OR'), name='favorite_exactly_one_target'),
        ),
    ]
