# Generated by Django 5.2.5 on 2025-09-24 23:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0027_shrine_location_placeref_placeref_snapshot_gin_and_more"),
    ]

    operations = [
        # レガシー unique_together を正式に撤廃（UniqueConstraint に統一）
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together=set(),
        ),
    ]
