# Generated by Django 5.2.5 on 2025-10-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0034_partial_unique_shrine_name_location"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shrine",
            constraint=models.UniqueConstraint(
                condition=models.Q(("location__isnull", False)),
                fields=("name_jp", "address", "location"),
                name="uq_shrine_name_loc",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrine",
            constraint=models.UniqueConstraint(
                condition=models.Q(("location__isnull", True)),
                fields=("name_jp", "address"),
                name="uq_shrine_name_addr_when_loc_null",
            ),
        ),
    ]
