# Generated by Django 5.2.7 on 2025-10-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0037_drop_dup_gist"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="favorite",
            name="fav_user_shrine_created",
        ),
        migrations.RemoveIndex(
            model_name="favorite",
            name="fav_user_created",
        ),
        migrations.AlterField(
            model_name="goriyakutag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
