# Generated by Django 5.2.7 on 2025-10-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0038_remove_favorite_fav_user_shrine_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("kana", models.CharField(blank=True, default="", max_length=128)),
                ("aliases", models.CharField(blank=True, default="", max_length=256)),
                ("wiki_url", models.URLField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
