# Generated by Django 5.2.7 on 2025-10-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0039_deity"),
    ]

    operations = [
        migrations.AddField(
            model_name="shrine",
            name="deities",
            field=models.ManyToManyField(blank=True, related_name="shrines", to="temples.deity"),
        ),
    ]
