# Generated by Django 5.2.7 on 2025-10-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0040_shrine_deities"),
    ]

    operations = [
        migrations.AddField(
            model_name="shrine",
            name="kyusei",
            field=models.CharField(
                blank=True,
                choices=[
                    ("一白水星", "一白水星"),
                    ("二黒土星", "二黒土星"),
                    ("三碧木星", "三碧木星"),
                    ("四緑木星", "四緑木星"),
                    ("五黄土星", "五黄土星"),
                    ("六白金星", "六白金星"),
                    ("七赤金星", "七赤金星"),
                    ("八白土星", "八白土星"),
                    ("九紫火星", "九紫火星"),
                ],
                help_text="九星（例: 九紫火星）",
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="shrine",
            index=models.Index(fields=["kyusei"], name="idx_shrine_kyusei"),
        ),
    ]
