# Generated by Django 5.2.7 on 2025-10-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0041_shrine_kyusei_shrine_idx_shrine_kyusei"),
    ]

    operations = [
        migrations.AddField(
            model_name="shrine",
            name="kind",
            field=models.CharField(
                choices=[("shrine", "神社"), ("temple", "寺院")],
                db_index=True,
                default="shrine",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="shrine",
            index=models.Index(fields=["kind"], name="idx_shrine_kind"),
        ),
    ]
