# Generated by Django 5.2.7 on 2025-10-11 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0042_shrine_kind_shrine_idx_shrine_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConciergeMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("role", models.CharField(max_length=10)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConciergeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="shrine",
            name="deities",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="shrine",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="user",
        ),
        migrations.RemoveField(
            model_name="shrine",
            name="goriyaku_tags",
        ),
        migrations.RemoveField(
            model_name="goshuin",
            name="shrine",
        ),
        migrations.RemoveField(
            model_name="goshuin",
            name="user",
        ),
        migrations.RemoveField(
            model_name="goshuinimage",
            name="goshuin",
        ),
        migrations.RemoveField(
            model_name="like",
            name="shrine",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.DeleteModel(
            name="PlaceRef",
        ),
        migrations.RemoveField(
            model_name="rankinglog",
            name="shrine",
        ),
        migrations.RemoveField(
            model_name="conciergehistory",
            name="shrine",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="shrine",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="user",
        ),
        migrations.RenameField(
            model_name="conciergehistory",
            old_name="reason",
            new_name="query",
        ),
        migrations.RemoveField(
            model_name="conciergehistory",
            name="tags",
        ),
        migrations.AddField(
            model_name="conciergehistory",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="conciergehistory",
            name="response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="conciergehistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="conciergemessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="temples.conciergesession"
            ),
        ),
        migrations.DeleteModel(
            name="Deity",
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
        migrations.DeleteModel(
            name="GoriyakuTag",
        ),
        migrations.DeleteModel(
            name="Goshuin",
        ),
        migrations.DeleteModel(
            name="GoshuinImage",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="RankingLog",
        ),
        migrations.DeleteModel(
            name="Shrine",
        ),
        migrations.DeleteModel(
            name="Visit",
        ),
    ]
