# Generated by Django 5.2.7 on 2025-11-09 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0044_deity_remove_conciergesession_user_and_more"),
        ("temples", "0045_add_location_state_only"),
    ]

    operations = []
