# Generated by Django 5.2.8 on 2025-12-01 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0049_goshuin_shrine"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goshuin",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="goshuin",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="goshuin",
            name="is_public",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="goshuin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goshuin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
