# Generated by Django 5.2.7 on 2025-12-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0054_fix_goshuin_user_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="goshuin",
            name="size_bytes",
            field=models.BigIntegerField(default=0),
        ),
    ]
