# Generated by Django 5.2.7 on 2025-12-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0055_goshuin_size_bytes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goshuin",
            name="size_bytes",
        ),
        migrations.AddField(
            model_name="goshuinimage",
            name="size_bytes",
            field=models.BigIntegerField(default=0),
        ),
    ]
