# Generated by Django 5.2.8 on 2025-12-13 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0056_remove_goshuin_size_bytes_goshuinimage_size_bytes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conciergethread",
            options={"ordering": ["-last_message_at", "-id"]},
        ),
        migrations.RemoveIndex(
            model_name="conciergethread",
            name="idx_thread_user_last",
        ),
        migrations.RenameIndex(
            model_name="conciergemessage",
            new_name="temples_con_thread__0068fd_idx",
            old_name="idx_msg_thread_created",
        ),
        migrations.RemoveField(
            model_name="conciergethread",
            name="last_message",
        ),
        migrations.RemoveField(
            model_name="conciergethread",
            name="message_count",
        ),
        migrations.AddField(
            model_name="conciergemessage",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="conciergethread",
            name="main_shrine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="concierge_threads",
                to="temples.shrine",
            ),
        ),
        migrations.AddField(
            model_name="conciergethread",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="conciergemessage",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("assistant", "Assistant"), ("system", "System")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="conciergethread",
            name="last_message_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="conciergethread",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddIndex(
            model_name="conciergethread",
            index=models.Index(
                fields=["user", "last_message_at"], name="temples_con_user_id_c38936_idx"
            ),
        ),
    ]
