# Generated by Django 5.2.8 on 2026-01-11 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0057_alter_conciergethread_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favorite",
            name="favorite_exactly_one_target",
        ),
        migrations.RemoveConstraint(
            model_name="favorite",
            name="uq_favorite_user_shrine",
        ),
        migrations.RemoveConstraint(
            model_name="favorite",
            name="uq_favorite_user_place",
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("shrine__isnull", False)),
                fields=("user", "shrine"),
                name="uniq_favorite_user_shrine",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("place_id__isnull", False)),
                fields=("user", "place_id"),
                name="uniq_favorite_user_place",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("shrine__isnull", False), ("place_id__isnull", True)),
                    models.Q(("shrine__isnull", True), ("place_id__isnull", False)),
                    _connector="OR",
                ),
                name="chk_favorite_exactly_one_target",
            ),
        ),
    ]
