# Generated by Django 5.2.8 on 2026-01-14 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0058_remove_favorite_favorite_exactly_one_target_and_more"),
        ("temples", "0059_shrine_astro_elements"),
    ]

    operations = []
