# Generated by Django 5.2.8 on 2026-01-14 09:17
# 0061_normalize_astro_elements_to_ja.py
from __future__ import annotations

from django.db import migrations

MAP = {
    "fire": "火",
    "water": "水",
    "earth": "土",
    "air": "風",
    # 既に日本語が入っていた場合はそのまま
    "火": "火",
    "水": "水",
    "土": "土",
    "風": "風",
}

def forwards(apps, schema_editor):
    Shrine = apps.get_model("temples", "Shrine")
    qs = Shrine.objects.all().only("id", "astro_elements")

    for s in qs.iterator():
        elems = s.astro_elements or []
        if not isinstance(elems, list):
            elems = []
        new_elems = []
        for e in elems:
            key = str(e).strip()
            if not key:
                continue
            new_elems.append(MAP.get(key, key))  # 未知値はそのまま
        # 重複除去（順序維持）
        seen = set()
        dedup = []
        for e in new_elems:
            if e in seen:
                continue
            seen.add(e)
            dedup.append(e)

        if dedup != elems:
            s.astro_elements = dedup
            s.save(update_fields=["astro_elements"])

def backwards(apps, schema_editor):
    Shrine = apps.get_model("temples", "Shrine")
    rev = {v: k for k, v in MAP.items() if k in ("fire", "water", "earth", "air")}
    # rev は {"火":"fire","水":"water","土":"earth","風":"air"}
    qs = Shrine.objects.all().only("id", "astro_elements")

    for s in qs.iterator():
        elems = s.astro_elements or []
        if not isinstance(elems, list):
            elems = []
        new_elems = []
        for e in elems:
            key = str(e).strip()
            if not key:
                continue
            new_elems.append(rev.get(key, key))
        # 重複除去（順序維持）
        seen = set()
        dedup = []
        for e in new_elems:
            if e in seen:
                continue
            seen.add(e)
            dedup.append(e)

        if dedup != elems:
            s.astro_elements = dedup
            s.save(update_fields=["astro_elements"])

class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0060_merge_20260114_1114"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
