# Generated by Django 5.2.8 on 2026-01-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0061_normalize_astro_elements_to_ja"),
    ]

    operations = [
        migrations.AddField(
            model_name="conciergethread",
            name="recommendations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conciergethread",
            name="recommendations_v2",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
