# Generated by Django 5.2.8 on 2026-01-27 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0062_conciergethread_recommendations_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="shrine",
            name="uq_shrine_name_loc",
        ),
        migrations.RemoveConstraint(
            model_name="shrine",
            name="uq_shrine_name_addr_when_loc_null",
        ),
        migrations.AddField(
            model_name="shrine",
            name="place_ref",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shrine",
                to="temples.placeref",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrine",
            constraint=models.UniqueConstraint(
                condition=models.Q(("location__isnull", False), ("place_ref__isnull", True)),
                fields=("name_jp", "address", "location"),
                name="uq_shrine_name_loc",
            ),
        ),
        migrations.AddConstraint(
            model_name="shrine",
            constraint=models.UniqueConstraint(
                condition=models.Q(("location__isnull", True), ("place_ref__isnull", True)),
                fields=("name_jp", "address"),
                name="uq_shrine_name_addr_when_loc_null",
            ),
        ),
    ]
