# Generated by Django 5.2.8 on 2026-01-30 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0063_remove_shrine_uq_shrine_name_loc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShrineCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "place_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                ("name_jp", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=512)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("goriyaku", models.CharField(blank=True, default="", max_length=255)),
                ("source", models.CharField(default="manual", max_length=64)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("imported", "Imported"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="temples_shr_status_9a0be4_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("place_id__isnull", False)),
                        fields=("place_id",),
                        name="uniq_candidate_place_id",
                    )
                ],
            },
        ),
    ]
