# Generated by Django 5.2.8 on 2026-01-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0064_shrinecandidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="shrinecandidate",
            name="synced_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
