# Generated by Django 5.2.8 on 2026-01-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0065_shrinecandidate_synced_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shrinecandidate",
            name="source",
            field=models.CharField(
                choices=[
                    ("resolve", "Resolve"),
                    ("manual", "Manual"),
                    ("places_find", "PlacesFind"),
                    ("stub", "Stub"),
                ],
                default="manual",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="shrinecandidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("approved", "Approved"),
                    ("imported", "Imported"),
                    ("rejected", "Rejected"),
                ],
                default="auto",
                max_length=16,
            ),
        ),
    ]
