# Generated by Django 5.2.8 on 2026-01-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temples", "0068_alter_shrinecandidate_source_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="shrinecandidate",
            name="uniq_candidate_place_id",
        ),
        migrations.AddConstraint(
            model_name="shrinecandidate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("place_id__isnull", False)),
                fields=("place_id", "status"),
                name="uniq_candidate_place_id",
            ),
        ),
    ]
