# Generated by Django 5.2.8 on 2026-02-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0069_alter_shrinecandidate_unique_place_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("place_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=512)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("user_ratings_total", models.IntegerField(blank=True, null=True)),
                ("types", models.JSONField(blank=True, default=list)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "place_cache",
                "indexes": [
                    models.Index(fields=["fetched_at"], name="place_cache_fetched_db467c_idx")
                ],
            },
        ),
    ]
