# Generated by Django 5.2.8 on 2026-02-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0070_place_cache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placecache",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
