# Generated by Django 5.2.8 on 2026-02-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0071_alter_placecache_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shrine",
            name="deities",
        ),
        migrations.AlterField(
            model_name="shrine",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
