# Generated by Django 5.2.8 on 2026-02-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0073_shrine_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlTile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("step_km", models.FloatField()),
                ("min_lat", models.FloatField()),
                ("min_lng", models.FloatField()),
                ("max_lat", models.FloatField()),
                ("max_lng", models.FloatField()),
                ("center_lat", models.FloatField()),
                ("center_lng", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("tries", models.PositiveIntegerField(default=0)),
                ("last_crawled_at", models.DateTimeField(blank=True, null=True)),
                ("next_page_token", models.CharField(blank=True, default="", max_length=256)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "last_crawled_at"], name="temples_cra_status_6524a9_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("step_km", "min_lat", "min_lng", "max_lat", "max_lng"),
                        name="uniq_crawltile_step_bbox",
                    )
                ],
            },
        ),
    ]
