# Generated by Django 5.2.8 on 2026-02-21 02:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0074_crawltile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacesSeed",
            fields=[
                ("seed_key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("pref_code", models.CharField(blank=True, default="", max_length=2)),
                ("pref", models.CharField(blank=True, default="", max_length=32)),
                ("label", models.CharField(blank=True, default="", max_length=32)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("radius_m", models.IntegerField(blank=True, null=True)),
                ("limit", models.IntegerField(blank=True, null=True)),
                ("keyword", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "places_seed",
            },
        ),
        migrations.CreateModel(
            name="PlacesSeedState",
            fields=[
                (
                    "seed",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="state",
                        serialize=False,
                        to="temples.placesseed",
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("ok", "OK"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("running", "Running"),
                        ],
                        db_index=True,
                        default="never",
                        max_length=16,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("last_requests_used", models.IntegerField(default=0)),
                ("last_upserted", models.IntegerField(default=0)),
                ("last_fetched", models.IntegerField(default=0)),
                ("total_runs", models.IntegerField(default=0)),
                ("total_requests_used", models.IntegerField(default=0)),
                ("total_upserted", models.IntegerField(default=0)),
                ("cooldown_until", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "places_seed_state",
            },
        ),
        migrations.AddIndex(
            model_name="placesseed",
            index=models.Index(
                fields=["pref_code", "label"], name="places_seed_pref_co_27f61e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placesseed",
            index=models.Index(
                fields=["is_active", "updated_at"], name="places_seed_is_acti_04817c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placesseedstate",
            index=models.Index(
                fields=["last_status", "last_run_at"], name="places_seed_last_st_b771ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placesseedstate",
            index=models.Index(fields=["cooldown_until"], name="places_seed_cooldow_b4ea36_idx"),
        ),
    ]
