# Generated by Django 5.2.8 on 2026-03-13 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0075_placesseed_placesseedstate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConciergeRecommendationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("query", models.TextField(blank=True, default="")),
                ("need_tags", models.JSONField(blank=True, default=list)),
                ("flow", models.CharField(blank=True, default="", max_length=8)),
                ("llm_enabled", models.BooleanField(default=False)),
                ("llm_used", models.BooleanField(default=False)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("result_state", models.JSONField(blank=True, default=dict)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("radius_m", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_logs",
                        to="temples.conciergethread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concierge_recommendation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "temples_concierge_recommendation_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConciergeRecommendationClickLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("shrine_id", models.IntegerField(blank=True, null=True)),
                ("place_id", models.CharField(blank=True, default="", max_length=255)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_click_logs",
                        to="temples.conciergethread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concierge_recommendation_click_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommendation_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_logs",
                        to="temples.conciergerecommendationlog",
                    ),
                ),
            ],
            options={
                "db_table": "temples_concierge_recommendation_click_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
