# Generated by Django 5.2.8 on 2026-03-22 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0076_conciergerecommendationlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("anonymous", "Anonymous"), ("user", "User")], max_length=16
                    ),
                ),
                ("anon_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("concierge", "Concierge"),
                            ("favorite", "Favorite"),
                            ("goshuin_upload", "Goshuin Upload"),
                        ],
                        max_length=32,
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["scope", "feature"], name="temples_fea_scope_16bb7d_idx"),
                    models.Index(fields=["user", "feature"], name="temples_fea_user_id_ed3ce9_idx"),
                    models.Index(
                        fields=["anon_id", "feature"], name="temples_fea_anon_id_6f0176_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "user"), ("user__isnull", False)),
                        fields=("user", "feature"),
                        name="uq_feature_usage_user_feature",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "anonymous"), ("anon_id__gt", "")),
                        fields=("anon_id", "feature"),
                        name="uq_feature_usage_anon_feature",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("scope", "user"), ("user__isnull", False), ("anon_id", "")),
                            models.Q(
                                ("scope", "anonymous"), ("user__isnull", True), ("anon_id__gt", "")
                            ),
                            _connector="OR",
                        ),
                        name="chk_feature_usage_scope_target",
                    ),
                ],
            },
        ),
    ]
