# Generated by Django 5.2.8 on 2026-03-26 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0077_featureusage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conciergethread",
            name="anonymous_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="conciergethread",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concierge_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="conciergethread",
            index=models.Index(
                fields=["anonymous_id", "last_message_at"], name="temples_con_anonymo_b4584d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="conciergethread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False), ("anonymous_id__isnull", False), _connector="OR"
                ),
                name="concierge_thread_user_or_anonymous_required",
            ),
        ),
    ]
