# Generated by Django 5.2.16 on 2026-09-12 07:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temples", "0105_w0b02t02_remove_qa_artifact_id102"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyPresentationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("anonymous_id", models.CharField(blank=True, max_length=64, null=True)),
                ("week_start", models.DateField()),
                ("purpose", models.CharField(max_length=32)),
                ("direction_fingerprint", models.CharField(max_length=64)),
                ("weekly_theme", models.JSONField(default=dict)),
                ("featured_shrine_ids", models.JSONField(blank=True, default=list)),
                ("presentation_version", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_presentation_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "temples_weekly_presentation_snapshot",
                "ordering": ["-week_start", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("user__isnull", False), ("anonymous_id__isnull", True)),
                            models.Q(("user__isnull", True), ("anonymous_id__isnull", False)),
                            _connector="OR",
                        ),
                        name="chk_weekly_presentation_snapshot_owner_xor",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=(
                            "user",
                            "week_start",
                            "purpose",
                            "direction_fingerprint",
                            "presentation_version",
                        ),
                        name="uq_weekly_presentation_snapshot_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("anonymous_id__isnull", False)),
                        fields=(
                            "anonymous_id",
                            "week_start",
                            "purpose",
                            "direction_fingerprint",
                            "presentation_version",
                        ),
                        name="uq_weekly_presentation_snapshot_anonymous",
                    ),
                ],
            },
        ),
    ]
