# Generated by Django 5.2.16 on 2026-09-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_userprofile_is_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="worship_style",
        ),
    ]
