# Generated by Django 5.2.16 on 2026-09-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_userprofile_worship_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
    ]
