import type { MeaningTag } from "./types";

export const psychologicalTags: MeaningTag[] = [
  {
    id: "stagnation_break",
    label: "停滞打破",
    category: "psychological",
    description: "止まってしまった流れを切り替え、動き出すきっかけを作りたい状態。",
    source: "manual",
    confidence: "high",
    relatedNeedTags: ["courage", "career", "money"],
    uiLabel: "停滞を断ち切る",
    note: "前に進みたいのに重さがある時の主題になりやすい。",
  },
  {
    id: "grounding",
    label: "気持ちを整える",
    category: "psychological",
    description: "焦りや揺れを静め、落ち着いて受け止め直したい状態。",
    source: "manual",
    confidence: "high",
    relatedNeedTags: ["mental", "recovery", "love"],
    uiLabel: "気持ちを整える",
    note: "勢いよりも安定を優先したい時に向く。",
  },
  {
    id: "recovery",
    label: "回復",
    category: "psychological",
    description: "疲れや消耗から戻り、立て直すための余白を必要としている状態。",
    source: "manual",
    confidence: "high",
    relatedNeedTags: ["mental", "recovery", "health"],
    uiLabel: "回復を優先する",
    note: "前進の前に休息や再調整が必要な段階。",
  },
  {
    id: "resolve",
    label: "覚悟を定める",
    category: "psychological",
    description: "迷いを減らし、腹を決めて進むための軸を定めたい状態。",
    source: "manual",
    confidence: "high",
    relatedNeedTags: ["career", "study", "courage"],
    uiLabel: "覚悟を定める",
    note: "決断前や目標設定前の整理に向きやすい。",
  },
  {
    id: "relationship_reset",
    label: "関係を整え直す",
    category: "psychological",
    description: "人間関係や縁の流れを見直し、つながり方を整え直したい状態。",
    source: "manual",
    confidence: "high",
    relatedNeedTags: ["love", "relationship", "family"],
    uiLabel: "関係を整え直す",
    note: "縁結びよりも、まず今の関係性の整理が主題になる時に使いやすい。",
  },
];
