import type { MeaningTag } from "./types";

export const turningPointTags: MeaningTag[] = [
  {
    id: "restart",
    label: "再出発",
    category: "turning_point",
    description: "一区切りの後で、新しい流れに入り直す節目。",
    source: "manual",
    confidence: "high",
    relatedNeedTags: ["career", "mental", "life"],
    uiLabel: "再出発の節目",
    note: "切り替えや立て直しの相談と接続しやすい。",
  },
  {
    id: "decision_point",
    label: "決断前",
    category: "turning_point",
    description: "進むか留まるか、方向を選ぶ前の局面。",
    source: "manual",
    confidence: "high",
    relatedNeedTags: ["career", "courage", "study"],
    uiLabel: "決断前の局面",
    note: "背中を押すより、決めるための整理に向きやすい。",
  },
  {
    id: "life_milestone",
    label: "人生の節目",
    category: "turning_point",
    description: "人生全体を見直したくなる大きな区切りや転換点。",
    source: "manual",
    confidence: "high",
    relatedNeedTags: ["life", "mental", "career"],
    uiLabel: "人生の節目",
    note: "個別課題よりも全体の流れを整える説明に向く。",
  },
  {
    id: "relationship_shift",
    label: "関係の転機",
    category: "turning_point",
    description: "縁や関係性が変わる局面で、結び直しや見直しが必要な段階。",
    source: "manual",
    confidence: "high",
    relatedNeedTags: ["love", "relationship", "family"],
    uiLabel: "関係の転機",
    note: "良縁だけでなく、関係の再編にも使える。",
  },
  {
    id: "goal_commitment",
    label: "目標設定",
    category: "turning_point",
    description: "散った意識をまとめて、どこへ向かうかを定め直す局面。",
    source: "manual",
    confidence: "high",
    relatedNeedTags: ["study", "career", "courage"],
    uiLabel: "目標を定める",
    note: "集中や覚悟の説明と相性が良い。",
  },
];
