name: backend-tests
permissions:
  contents: read

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: jdb50515
          POSTGRES_DB: jinja_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U admin -d jinja_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DJANGO_SETTINGS_MODULE: shrine_project.settings
      USE_GIS: "1"
      USE_LLM_CONCIERGE: "0"
      AUTO_GEOCODE_ON_SAVE: "0"
      DATABASE_URL: postgis://admin:jdb50515@localhost:5432/jinja_test
      DJANGO_SECRET_KEY: ci-only-secret
      GOOGLE_PLACES_API_KEY: dummy
      GOOGLE_MAPS_API_KEY: dummy
      ROUTE_PROVIDER: dummy
      PYTHONDONTWRITEBYTECODE: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (GDAL/GEOS + pg client)
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev libgeos-dev postgresql-client

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements-dev.txt

      - name: Wait for DB
        run: |
          for i in {1..60}; do
            pg_isready -h localhost -p 5432 -U admin -d jinja_test && break
            echo "waiting for Postgres... ($i/60)"
            sleep 2
          done
          pg_isready -h localhost -p 5432 -U admin -d jinja_test

      - name: Run tests via Makefile (repo root)
        working-directory: .
        run: make test
