# .github/workflows/backend-tests.yml
name: Backend Tests (minimal)

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-tests.yml"
  push:
    branches: ["develop", "main", "feature/**", "ci/**"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_DB: jinja_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U admin -d jinja_db"
          --health-interval=10s --health-timeout=5s --health-retries=10
      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install system deps (GDAL minimal)
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev libgeos-dev proj-bin
          sudo apt-get install -y postgresql-client

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          if [ -f backend/requirements-dev.txt ]; then pip install -r backend/requirements-dev.txt; fi

      - name: Lint (black --check & ruff)
        working-directory: backend
        run: |
          black --check .
          ruff check .

      - name: Export env for app/tests
        run: |
          echo "DB_NAME=jinja_db" >> $GITHUB_ENV
          echo "DB_USER=admin" >> $GITHUB_ENV
          echo "DB_PASSWORD=postgres" >> $GITHUB_ENV
          # 念のため同じ値を POSTGRES_* にも（settings が参照する場合の保険）
          echo "POSTGRES_DB=jinja_db" >> $GITHUB_ENV
          echo "POSTGRES_USER=admin" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=postgres" >> $GITHUB_ENV


          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV

          echo "REDIS_URL=redis://127.0.0.1:6379/0" >> $GITHUB_ENV
          echo "USE_GIS=1" >> $GITHUB_ENV
          echo "AUTO_GEOCODE_ON_SAVE=0" >> $GITHUB_ENV
          echo "GEOCODER_PROVIDER=google" >> $GITHUB_ENV
          echo "GOOGLE_MAPS_API_KEY=test-key" >> $GITHUB_ENV
          echo "PRINT_EFFECTIVE_SETTINGS=1" >> $GITHUB_ENV
          # 重要：テスト動作を安定化
          echo "IS_PYTEST=1" >> $GITHUB_ENV
          echo "PLACES_USE_FINDPLACE=1" >> $GITHUB_ENV

          # 重要：DATABASE_URL を無効化（もし settings が優先する実装なら干渉されないようにする）
          echo "DATABASE_URL=" >> $GITHUB_ENV

      - name: Wait for DB & enable PostGIS
        env:
          PGPASSWORD: ${{ env.DB_PASSWORD }}
        run: |
          for i in `seq 1 30`; do
            (echo > /dev/tcp/127.0.0.1/5432) >/dev/null 2>&1 && break
            echo "waiting for postgres..."; sleep 1
          done
          psql -h 127.0.0.1 -U "$DB_USER" -d "$DB_NAME" -c "CREATE EXTENSION IF NOT EXISTS postgis;"

      - name: Migrate
        working-directory: backend
        run: python manage.py migrate --noinput

      - name: Pytest (quiet)
        working-directory: backend
        env:
          # 念のため step env を明示
          IS_PYTEST: "1"
          PLACES_USE_FINDPLACE: "1"
        run: pytest -q --maxfail=1 --disable-warnings

      - name: Run mypy (allowlist)
        working-directory: backend
        env:
          DJANGO_SETTINGS_MODULE: shrine_project.settings
        run: |
          mypy --config-file mypy.ini \
          temples/services/google_places.py \
          temples/permissions.py
