name: backend tests
on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build & test
        run: |
          docker compose -f ../docker-compose.yml up -d --build db web
          docker compose -f ../docker-compose.yml exec -T web pytest -q
      - name: Tear down
        if: always()
        run: docker compose -f ../docker-compose.yml down -v
