# .github/workflows/backend-tests.yml
name: Backend Tests

on:
  pull_request:
    paths:
      - "backend/**"
      - "pyproject.toml"
      - "requirements*.txt"
      - ".github/workflows/backend-tests.yml"
  push:
    branches:
      - "ci/**"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: app
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U app"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run pytest
        working-directory: backend
        env:
          DATABASE_URL: postgresql://app:app@localhost:5432/app
        run: pytest -q --maxfail=1 --disable-warnings

      - name: Upload pytest cache/logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-artifacts
          path: |
            backend/.pytest_cache
            backend/.coverage
            backend/tests/.pytest_cache
