name: CI
permissions:
  contents: read

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  backend:
    runs-on: ubuntu-latest

    # PostGIS入りのDBを1つだけ定義（PG16）
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_DB: jinja_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: jdb50515
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin -d jinja_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 60
          --health-start-period 60s

    # Django が読む環境変数（ここも1つに統一）
    env:
      CI: "true"
      DJANGO_SETTINGS_MODULE: shrine_project.settings
      USE_GIS: "1"
      USE_LLM_CONCIERGE: "0"
      AUTO_GEOCODE_ON_SAVE: "0"
      # services で 5432 をホストに公開してるので localhost でOK
      DATABASE_URL: postgis://admin:jdb50515@localhost:5432/jinja_db
      DJANGO_SECRET_KEY: ci-only-secret
      GOOGLE_MAPS_API_KEY: "dummy"
      PYTHONDONTWRITEBYTECODE: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      ROUTE_PROVIDER: "dummy"   # ← 追加：テストをローカルと同条件に固定

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (GDAL/GEOS + pg client)
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev libgeos-dev postgresql-client

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Wait for DB (defensive)
        run: |
          for i in {1..90}; do
            pg_isready -h localhost -p 5432 -U admin -d jinja_db && break
            echo "⏳ waiting for Postgres... ($i/90)"
            sleep 2
          done
          pg_isready -h localhost -p 5432 -U admin -d jinja_db

      - name: Debug Django settings
        run: |
          python - <<'PY'
          import os, django
          os.environ.setdefault("DJANGO_SETTINGS_MODULE", "shrine_project.settings")
          django.setup()
          from django.conf import settings
          db = settings.DATABASES["default"]
          print("DB ENGINE:", db.get("ENGINE"))
          print("DB NAME  :", db.get("NAME"))
          print("DB USER  :", db.get("USER"))
          print("DB HOST  :", db.get("HOST"))
          print("DB PORT  :", db.get("PORT"))
          print("ROUTE_PROVIDER:", os.environ.get("ROUTE_PROVIDER"))
          PY

      - name: Migrate
        run: python manage.py migrate --noinput

      - name: Test
        run: pytest -q -p no:flake8

      - name: Show DB container logs (always)
        if: always()
        run: |
          docker ps -a --format '{{.ID}} {{.Image}} {{.Names}} {{.Status}}'
          CID="$(docker ps -a --filter 'ancestor=postgis/postgis:16-3.4' --format '{{.ID}}' | head -n1)"
          if [ -n "$CID" ]; then
            echo "==== docker inspect (health) ===="
            docker inspect "$CID" --format '{{json .State.Health}}' | jq . || true
            echo "==== docker logs $CID ===="
            docker logs "$CID" || true
          else
            echo "No postgis container found"
          fi
