name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgis/postgis:16-3.4
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: ${{ vars.DB_NAME }}
          POSTGRES_USER: ${{ vars.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd="pg_isready -U ${{ vars.DB_USER }} -d ${{ vars.DB_NAME }}"
          --health-interval=10s --health-timeout=5s --health-retries=12

    env:
      CI: "true"
      DJANGO_SETTINGS_MODULE: shrine_project.settings
      USE_GIS: "1"
      DB_HOST: "127.0.0.1"
      DB_PORT: "5432"
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      GOOGLE_MAPS_API_KEY: dummy
      PYTHONDONTWRITEBYTECODE: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install GDAL/GEOS system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev libgeos-dev


      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django responses
          pip install ruff mypy flake8 || true


      - name: Collect static
        run: python manage.py collectstatic --noinput

      - name: Migrate
        run: python manage.py migrate --noinput

      - name: Test
        run: pytest -q -p no:flake8
