name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Lint/Type/Tests
          pip install ruff mypy flake8 pytest pytest-django

      - name: Lint (ruff)
        run: ruff check .

      - name: Lint (flake8)
        run: flake8 .

      - name: Type-check (mypy)
        run: mypy temples || true  # 段階導入。まずはCIを赤くしない

      - name: Test
        env:
          DJANGO_SETTINGS_MODULE: shrine_project.settings
        run: |
          pytest -q
