# Updated workflow to remove working-directory
name: Django CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django test
        env:
          DJANGO_SETTINGS_MODULE: backend.shrine_project.settings

        run: |
          cd $GITHUB_WORKSPACE
          python backend/manage.py test -v 2


