name: backend-tests

on:
  push:
    branches: [ develop, main, api/** ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgis/postgis:16-3.4
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: jinja_app
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: jdb50515
        options: >-
          --health-cmd="pg_isready -U admin -d jinja_app"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      # Django設定で拾う環境変数
      DB_NAME: jinja_app
      DB_USER: admin
      DB_PASSWORD: jdb50515
      DB_HOST: localhost
      DB_PORT: 5432
      USE_GIS: "1"
      AUTO_GEOCODE_ON_SAVE: "0"
      GEOCODER_PROVIDER: "google"
      GOOGLE_MAPS_API_KEY: "test-key"  # 実呼び出しはしない想定
      PRINT_EFFECTIVE_SETTINGS: "1"

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (GDAL/GEOS/PROJ)
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev libgeos-dev proj-bin

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Python deps
        run: |
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Migrate
        run: |
          python manage.py migrate --noinput

      - name: Run tests
        run: |
          python manage.py test -v 2
